controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\UsersLogin;
use app\models\UsersReg;
use app\models\BooksSearch;
use app\models\BooksSearchUsers;
use app\models\BooksSearchHistory;
use app\models\BooksSearchStatistic;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['reg', 'login', 'logout', 'book-users', 'history', 'satistic'],
                'rules' => [
	                [//статистику и испорию смотреть может только admin
                        'actions' => ['satistic', 'history'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [//страница должников доступна только авторизованным
                        'actions' => ['book-users', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['reg', 'login'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ]
            ]
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

	/*Страница книг*/
	public function actionIndex() {
		$dataProvider = (new BooksSearch())->search();

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница должников*/
	public function actionBookUsers() {
		$dataProvider = (new BooksSearchUsers())->search();

		return $this->render('book_users', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница истории выдачи книг*/
	public function actionHistory() {
		$dataProvider = (new BooksSearchHistory())->search();

		return $this->render('book_users_history', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница статистики*/
	public function actionStatistic() {
		$statisticArray = (new BooksSearchStatistic())->search();

		return $this->render('book_statistic', [
			'statistic' => $statisticArray,
		]);
	}

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new UsersLogin();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	public function actionReg() {
		$model = new UsersReg();

		if ($model->load(\Yii::$app->request->post()) && $model->registration()) {
			return $this->goHome();
		} else {
			return $this->render('reg', [
				'model' => $model,
			]);
		}
	}
}

views/layouts/_nav_bar.php
<?php
/*Created by Edik (14.10.2015 14:38)*/
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
?>

<?php
    NavBar::begin([
        'brandLabel' => 'Библиотека',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-top navbar-inverse navbar-relative-top',
        ],
    ]);
?>

<?php if (Yii::$app->user->isGuest): ?>
    <?=
        Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Вход', 'url' => ['/site/login']],
                ['label' => 'Регистрация', 'url' => ['/site/reg']]
            ],
        ]);
    ?>
<?php else: $isAdmin = Yii::$app->user->can('admin'); ?>
	<?=
	    Nav::widget([
	        'options' => ['class' => 'navbar-nav navbar-left'],
	        'items' => [
		        ['label' => 'Выданные книги', 'url' => ['/site/book-users']],
		        ['label' => 'История выдачи', 'url' => ['/site/history'], 'visible' => $isAdmin],
		        ['label' => 'Статистика', 'url' => ['/site/statistic'], 'visible' => $isAdmin]
	        ],
	    ]);
	?>

    <?=
        Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
	            ['label' => 'Админка', 'url' => ['/admin'], 'active' => $this->context->module->id === 'admin', 'visible' => $isAdmin],
                ['label' => 'Выход (' . Yii::$app->user->identity->firstname . ')', 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']],
            ],
        ]);
    ?>
<?php endif; ?>

<?php
    NavBar::end();
?>

views/layouts/main.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>

	<?php $this->beginBody() ?>
	<div class="wrap">

		<?= $this->render('_nav_bar') ?>

		<div class="container">
			<?= $content ?>
		</div>
	</div>

	<footer class="footer">
		<div class="container">
			<p class="pull-left">&copy; Library <?= date('Y') ?></p>

			<p class="pull-right"><?= Yii::powered() ?></p>
		</div>
	</footer>

	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>