controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\BookUsers;
use app\models\BookUsersHistory;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class AjaxController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['get-book', 'return-book'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
	                'get-book' => ['post'],
	                'return-book' => ['post']
                ]
            ]
        ];
    }

	//ajax запрос с главной страницы при нажатии на кнопку "взять книгу"
	public function actionGetBook()
	{
		$idBook = Yii::$app->request->post('id_book');
		if ($idBook){
			$model = new BookUsers();
			$model->load(['id_user' => Yii::$app->user->id, 'id_book' => $idBook], '');
			$result = $model->save(false);
		} else {
			$result = false;
		}

		return json_encode(['result' => $result]);
	}

	//ajax запрос со страницы выданных книг при нажатии на кнопку "вернуть книгу"
	public function actionReturnBook(){
		$idBook = Yii::$app->request->post('id_book');
		if ($idBook){
			$model = BookUsers::findOne(['id_book' => $idBook]);

			$newModel = new BookUsersHistory();
			$newModel->load(['id_user' => $model->id_user, 'id_book' => $idBook, 'date_add' => $model->date_add], '');
			$result = $newModel->save(false);

			if ($result) $model->delete();
		} else {
			$result = false;
		}

		return json_encode(['result' => $result]);
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\UsersLogin;
use app\models\UsersReg;
use app\models\BooksSearch;
use app\models\BooksSearchUsers;
use app\models\BooksSearchHistory;
use app\models\BooksSearchStatistic;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['reg', 'login', 'logout', 'book-users', 'history', 'satistic'],
                'rules' => [
	                [//статистику и испорию смотреть может только admin
                        'actions' => ['satistic', 'history'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [//страница должников доступна только авторизованным
                        'actions' => ['book-users', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['reg', 'login'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ]
            ]
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

	/*Страница книг*/
	public function actionIndex() {
		$dataProvider = (new BooksSearch())->search();

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница должников*/
	public function actionBookUsers() {
		$dataProvider = (new BooksSearchUsers())->search();

		return $this->render('book_users', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница истории выдачи книг*/
	public function actionHistory() {
		$dataProvider = (new BooksSearchHistory())->search();

		return $this->render('book_users_history', [
			'dataProvider' => $dataProvider,
		]);
	}

	/*Страница статистики*/
	public function actionStatistic() {
		$statisticArray = (new BooksSearchStatistic())->search();

		return $this->render('book_statistic', [
			'statistic' => $statisticArray,
		]);
	}

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new UsersLogin();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	public function actionReg() {
		$model = new UsersReg();

		if ($model->load(\Yii::$app->request->post()) && $model->registration()) {
			return $this->goHome();
		} else {
			return $this->render('reg', [
				'model' => $model,
			]);
		}
	}
}

views/site/_item_book_users.php
<?php
/**
 *  @var array $model
 */
?>


<h4><?=$model['name']; ?></h4>

<div class="issued-book__content">
	<span class="issued-book__content__user">
		<span class="issued-book__content__user__name"><?=$model['firstname']; ?></span> взял книгу <?=$model['date_add']; ?>
	</span>

		<button class="issued-book__content__button btn-disabled" onclick="books.returnBook('/ajax/return-book', <?=$model['id_book']?>, this)">
			<?php if ($model['id_user'] == \Yii::$app->user->id): ?>
				Вернуть книгу
			<?php elseif (\Yii::$app->user->can('admin')): ?>
				Книгу вернули
			<?php endif; ?>
		</button>
</div>

views/site/_item_book_users_history.php
<?php
/**
 *  @var app\models\BookUsersHistory $model
 */
?>


<h4><?= $model->book->name ?></h4>
<div>
	<?php if ($model->user): ?>
		Выдано: <?= $model->user->firstname ?>
	<?php else: ?>
		Пользователь удален
	<?php endif; ?>
</div>
<div>
	Дата выдачи: <?= $model->date_add ?>
</div>
<div>
	Дата возврата: <?= $model->date_return ?>
</div>

views/site/_item_index.php
<?php
/**
 *  @var app\models\BooksSearch $model
 */
use yii\helpers\Html;

?>

<div class="book__header">
	<h3 class="book__header__h"><?=$model->name; ?></h3>
	<div class="book__header__status book__header__status_id-status_<?=$model->id_status?>"><?= $model->getStatusName(); ?></div>
</div>

<div class="book__authors">
	<?php foreach ($model->bookAuthors as $author): ?>
		<span class="book__authors__name"><?=$author->firstname?> <?=$author->lastname?> <?=$author->patronymic?></span>
	<?php endforeach; ?>
</div>

<div class="book__desc">
	<?= $model->description ?>
</div>

<div class="book__bottom">
	<div class="book__bottom__buttons">
		<?php if ($model->id_status == 1): ?>
			<?php if (\Yii::$app->user->isGuest): ?>
			    Что бы взять книгу нужно <?= Html::a('авторизоваться', ['login']) ?>
			<?php else: ?>
				<button class="btn-disabled" onclick="books.getBook('/ajax/get-book', <?=$model->id_book?>, this)">Взять книгу</button>
			<?php endif; ?>
		<?php else: ?>
			<button class="btn-disabled" disabled>Книга выдана</button>
		<?php endif; ?>
	</div>
</div>

views/site/book_statistic.php
<?php
/* @var $this yii\web\View */
/* @var array $statistic */

$this->title = 'Статистика';
?>
<div class="site-index">

	<div>
		<div>
			<h3>Статистика по книгам</h3>
			<?php $allListStatuses = \app\models\BookStatuses::findAllList() ?>
			<?php foreach ($statistic['countBooks'] as $idStatus => $count): ?>
			    <?= $allListStatuses[$idStatus] ?>: <?=$count?> <br>
			<?php endforeach; ?>
		</div>
		<div>
			<h3>Статистика по должникам</h3>
			Количество должников: <?=$statistic['countUsers']?>
		</div>
	</div>

</div>

views/site/book_users.php
<?php
/* @var $this yii\web\View */
/* @var yii\data\ActiveDataProvider $dataProvider */
use yii\widgets\ListView;

$this->title = 'Выданные книги';
?>
<div class="site-index">

    <h1><?=$this->title?></h1>

    <div class="books-count">
	    Всего книг: <span class="books-count__number"><?= $dataProvider->totalCount ?></span>
    </div>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{items}\n{pager}",
        'emptyText' => '',
        'itemView' => '_item_book_users',
        'itemOptions' => ['class' => 'issued-book']
    ]); ?>
</div>

views/site/book_users_history.php
<?php
/* @var $this yii\web\View */
/* @var yii\data\ActiveDataProvider $dataProvider */
use yii\widgets\ListView;

$this->title = 'История выдачи';
?>
<div class="site-index">

    <h1><?=$this->title?></h1>

    <div class="books-count">
	    Всего позиций: <span class="books-count__number"><?= $dataProvider->totalCount ?></span>
    </div>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{items}\n{pager}",
        'emptyText' => '',
        'itemView' => '_item_book_users_history',
        'itemOptions' => ['class' => 'issued-book']
    ]); ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
/* @var yii\data\ActiveDataProvider $dataProvider */
use yii\widgets\ListView;

$this->title = 'Библиотека';
?>
<div class="site-index">

    <h1><?=$this->title?></h1>

    <div class="books-count">
	    Всего книг: <span class="books-count__number"><?= $dataProvider->totalCount ?></span>
    </div>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{items}\n{pager}",
        'emptyText' => '',
        'itemView' => '_item_index',
        'options' => ['class' => 'books'],
        'itemOptions' => ['class' => 'book']
    ]); ?>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\UsersLogin */

$this->title = 'Вход';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>


    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/reg.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\UsersReg */

$this->title = 'Регистрация';
?>
<div class="site-reg">
    <h1><?= Html::encode($this->title) ?></h1>


    <?php $form = ActiveForm::begin([
        'id' => 'reg-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

	<?= $form->field($model, 'firstname') ?>

	<?= $form->field($model, 'lastname') ?>

	<?= $form->field($model, 'patronymic') ?>

	<?= $form->field($model, 'email') ?>

	<?= $form->field($model, 'password')->passwordInput() ?>

	<?= $form->field($model, 'passwordRepeat')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'reg-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>